### ISSUE TITLE
Only one device?

### ISSUE THREAD

**Issue by djamps** [LorenzoVasi/HA_mdadm#4]
I tried using multiple device: entries on a single sensor, as well as multiple binary_sensor: entries with a single device: but only one raid dev shows up in HA.

**Comment by LorenzoVasi** [comment]
Hola!
Could you give me your configuration.yaml and your HA version? 
Are you using HASSIO or another OS? 
Thanks

**Comment by djamps** [comment]
HA: 2024.1.5

First try on configuration.yaml:
```
binary_sensor:
  - platform: mdadm_state
    device: md0

binary_sensor:
  - platform: mdadm_state
    device: md1

binary_sensor:
  - platform: mdadm_state
    device: md2
```

2nd try:

```
binary_sensor:
  - platform: mdadm_state
    device: md0
    device: md1
    device: md2
```
Both will only expose one of the devices.

**Comment by djamps** [comment]
Forgot to mention, using HACS, and it's not HASSIO, it's a native ubuntu base OS with HA running in Docker.

**Comment by LorenzoVasi** [comment]
Try with this formattation

```yaml

binary_sensor:
  - platform: mdadm_state
    device: md0
  - platform: mdadm_state
    device: md1
  - platform: mdadm_state
    device: md2

```

Text me if it works 👍🏻
